# NUMPY LIBRARY

###### NumPy is short for "Numerical Python".NumPy was created in 2005 by Travis Oliphant.NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

https://numpy.org/doc/stable/reference/arrays.html

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
print(np.__version__)

1.22.1


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) # we can create an ndarray( array obj in numpy ) using array() function 
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5)) #using a tuple to create numpy array.
print(arr)

[1 2 3 4 5]


In [16]:
# 0 D Array
import numpy as np
arr = np.array(42)
print("0D-",arr)
print(arr.ndim)
print("")
print("")

# 1 D Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("1D-",arr)
print(arr.ndim)
print("")
print("")

# 2 D Array 
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]]) # Array having 1d array as elements
print("2D-",arr)
print(arr.ndim)
print("")
print("")

# 3 D Array 
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("3D-",arr)
print(arr.ndim)
print("")
print("")


0D- 42
0


1D- [1 2 3 4 5]
1


2D- [[1 2 3]
 [4 5 6]]
2


3D- [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3




In [2]:
import numpy as np

In [3]:
#Higher order dimension

import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [4]:
a=np.array([1,2,3], dtype='int16')           #run import statement for accessing the alias np
print (a)

[1 2 3]


In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
#Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [7]:
#Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [8]:
#Get type
print(a.dtype)
print(b.dtype)

int16
int32


In [9]:
#Get size
print(a.itemsize)
print(b.itemsize)

2
4


In [10]:
#get total size
print(a.nbytes)
print(b.nbytes)

6
24


### Accessing /changing specific elements ,rows,columns,etc


In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
#Get a specific element[r,c]
a[1,5]

13

In [17]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# get a specific column
a[:,2]

array([ 3, 10])

In [4]:
a[ 0,1:-1:2]   #{ [start index : end index :stepsize]}
a[ 0,1:6:2]

array([2, 4, 6])

In [2]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


3 d-example

In [10]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# getting specific element
b[0,1,1]

4

In [12]:
# replace
b[:,1,:]=[[9,9]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]


### initializing different types of arrays

In [16]:
# all 0 matrix
np.zeros((2,2))
#print(" ")

array([[0., 0.],
       [0., 0.]])

In [17]:

np.zeros((2,3))
#print(" ")

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:

np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# all 1's matrix

np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.ones((5,2) , dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [22]:
# any other number
np.full((2,2) ,9999)

array([[9999, 9999],
       [9999, 9999]])

In [24]:
#random decimal numbers
np.random.rand(4,2)

array([[0.29012289, 0.43529765],
       [0.59434   , 0.43598288],
       [0.30219304, 0.46041802],
       [0.30307791, 0.28664191]])

In [28]:
np.random.randint(-4,8,size=(3,3))

array([[ 4,  1,  6],
       [ 7,  0, -3],
       [ 2,  6, -1]])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
#repeat an array
import numpy as np

arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [2]:
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
print(z)
print(" ")

z[1,1]=9
print(z)

print(" ")
 
output[1:-1,1:-1] = z 
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
#Be careful in copying arrays

a=np.array([1,2,3,4])
b=a.copy()
b[0]=100
print(a)
print(b)


[1 2 3 4]
[100   2   3   4]


In [17]:
a=np.array([1,2,3,4])
print(a+2)
print(' ')
print(a-2)
print(" ")
print(a*2)
print(' ')
print(a//2)
print(" ")
print(a**2)
print(" ")

print(" ")

b=np.array([1,0,1,0])
print(a+b)

a**2

[3 4 5 6]
 
[-1  0  1  2]
 
[2 4 6 8]
 
[0 1 1 2]
 
[ 1  4  9 16]
 
 
[2 2 4 4]


array([ 1,  4,  9, 16])

In [18]:
# take the sin 
np.cos(a)


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [1]:
import numpy as np
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [2]:
# determinant of 1 d array
c=np.identity(3)
np.linalg.det(c)

1.0

In [3]:
# determinant of 2 d array
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

In [4]:
# trace

              #numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None) all are optional
              #Return the sum along diagonals of the array.
        
np.trace(a)
     

5

In [5]:
#eigenvalues   

np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [6]:
#inverse 
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.linalg. inv(a) 


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Statistics

In [7]:
stats=np.array([[1,2,3] ,[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.min(stats)

1

In [9]:
np.max(stats,axis=1)

array([3, 6])

In [10]:
np.sum(stats,axis=0)


array([5, 7, 9])

In [12]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(" ")
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
#vertically stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
#horizontal stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.hstack([v1,v2,v1,v2])


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
#horizontal stack

h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

In [23]:
#Load data from file
import numpy as np
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata.astype('int16')

print(filedata)

[ nan   2.   3.   4.   5.   6.   7.   8.   9.  10.  22.   2.   7.  78.
  11.  32.   0. 567.  24.  67.  81.  22.   5.  nan]


In [10]:
#Boolean masking and advanced learning
filedata > 50


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True,  True, False, False, False])

In [25]:
filedata[filedata>50]

array([ 78., 567.,  67.,  81.])

In [27]:
np.any(filedata>50,axis=0)

True

In [28]:
((filedata>50) & (filedata<100))

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True,  True, False, False, False])